name: "Setup node and install dependencies"
description: "sets up Node.js, caches dependencies, and installs them"
inputs:
  node-version:
    description: "Node.js version"
    required: false
    default: "22"
runs:
  using: composite
  steps:
    - name: setup node js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }} 
    - name: Cache dependencies
      uses: actions/cache@v4
      id: cache
      with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}     
    - name: Install Dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: npm install  
      shell: bash